name: Hacker News Digest

on:
  schedule:
    - cron: '0 9 * * 1'  # Weekly on Monday at 09:00 UTC
  workflow_dispatch:

permissions:
  contents: write  # Required to commit/push to the repo

jobs:
  daily-digest:
    runs-on: ubuntu-latest

    env:
      MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
      MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
      EMAIL_RECIPIENT: ${{ vars.EMAIL_RECIPIENT }}
      TOP_N: 20
      HETZNER_ACCESS_KEY: ${{ secrets.HETZNER_ACCESS_KEY }}
      HETZNER_SECRET_KEY: ${{ secrets.HETZNER_SECRET_KEY }}
      HETZNER_ENDPOINT: ${{ secrets.HETZNER_ENDPOINT }}
      HETZNER_BUCKET: ${{ secrets.HETZNER_BUCKET }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper and export digest URL
        id: scrape
        run: python scraper.py

      - name: Download digest from Hetzner
        run: |
          DIGEST_DATE=$(date -u +%Y-%m-%d)
          DIGEST_FILE="hn-digest-${DIGEST_DATE}.csv"
          mkdir -p docs/data
          curl -s "${{ steps.scrape.outputs.digest_url }}" -o "docs/data/$DIGEST_FILE"

      - name: Update digest index
        run: |
          DIGEST_DATE=$(date -u +%Y-%m-%d)
          DIGEST_FILE="hn-digest-${DIGEST_DATE}.csv"

          if [ ! -f docs/digest.json ]; then echo "[]" > docs/digest.json; fi

          jq --arg date "$DIGEST_DATE" --arg file "$DIGEST_FILE" \
            'map(select(.date != $date)) | [{"date": $date, "csv": "data/\($file)"}] + .' \
            docs/digest.json > docs/digest.tmp.json

          mv docs/digest.tmp.json docs/digest.json

      - name: Commit updated digest
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/data docs/digest.json
          git commit -m "Update digest for $(date -u +%Y-%m-%d)" || echo "No changes to commit"
          git push